---
title: "Klaster DAPODIK Semester Genap TA 2021/2022 Provinsi Papua"
author: "Afnita Rahma Auliya Putri"
date: '2022-06-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
library(factoextra)
library(ppclust)
library(cluster)
library(fclust)
library(readxl)
```

# Klaster Kecamatan

```{r}
# Memasukkan data
data <- read_excel("D:/Diunggah di GitHub/Data Pendidikan Provinsi Papua Kemendikbud (2).xlsx",  sheet = "Untuk Klaster")

# remove rows with missing values
# df <- na.omit(data) # di data (excel) sudah dihilangkan terlebih dahulu wilayah yang belum ada informasinya, sehingga tidak perlu lagi dilakukan ini

# scale each variable to have a mean of 0 and sd of 1
data_scale <- scale(data[3:8])

# view first six rows of dataset
head(data_scale)
```

# Pencarian k optimal, dalam penelitian ini menggunakan metode elbow dan silhouette

```{r}
# Elbow Method
fviz_nbclust(data_scale, fanny, method = "wss") +
  geom_vline(xintercept = 2, linetype = 2)
  labs(subtitle = "Elbow method for Optimal Cluster")


# Silhouette Method
fviz_nbclust(data_scale, fanny, method = "silhouette") +
  labs(subtitle = "Silhouette method for Optimal Cluster")
```

# Membuat klaster dengan jumlah klaster 2

```{r}
# make this example reproducible
set.seed(1)

# perform k-means clustering with k = 2 clusters
km <- kmeans(data_scale, centers = 2, nstart = 25)

# view results
km
```

```{r}
#plot results of final k-means model
fviz_cluster(km, data = data_scale, geom = "point")
```

```{r}
#find means of each cluster
aggregate(data, by=list(cluster=km$cluster), mean)
```

```{r}
#add cluster assigment to original data
final_data <- cbind(data, cluster = km$cluster)

#view final data
head(final_data)
```

# Klaster Kabupaten

```{r}
# Memasukkan data
data <- read_excel("D:/Diunggah di GitHub/Data Pendidikan Provinsi Papua Kemendikbud (2).xlsx",  sheet = "Tabel Merge")

data <- data[,-c(2:10)]

# remove rows with missing values
# df <- na.omit(data) # tidak perlu karena tidak ada missing values

# scale each variable to have a mean of 0 and sd of 1
data_scale <- scale(data[2:7])

# view first six rows of dataset
head(data_scale)
```

# Pencarian k optimal, dalam penelitian ini menggunakan metode elbow dan silhouette

```{r}
# Elbow Method
fviz_nbclust(data_scale, fanny, method = "wss") +
  geom_vline(xintercept = 2, linetype = 2)
  labs(subtitle = "Elbow method for Optimal Cluster")


# Silhouette Method
fviz_nbclust(data_scale, fanny, method = "silhouette") +
  labs(subtitle = "Silhouette method for Optimal Cluster")
```

# Membuat klaster dengan jumlah klaster 2

```{r}
# make this example reproducible
set.seed(1)

# perform k-means clustering with k = 2 clusters
km <- kmeans(data_scale, centers = 2, nstart = 25)

# view results
km
```

```{r}
#plot results of final k-means model
fviz_cluster(km, data = data_scale, geom = "point")
```

```{r}
#find means of each cluster
aggregate(data, by=list(cluster=km$cluster), mean)
```

```{r}
#add cluster assigment to original data
final_data <- cbind(data, cluster = km$cluster)

#view final data
head(final_data)
```


